require: 'rubocop-rspec'

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['#.*']
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()' # covers `%q`, `%Q`, `%s`, and `%x`
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
    '%i': '[]'
    '%I': '[]'
